export const UPDATE_CURRENT_TASKS = "UPDATE_CURRENT_TASKS";
export const UPDATE_TOTAL = "UPDATE_TOTAL";
export const INCREMENT_PAGE = "UPDATE_PAGE";
export const UPDATE_SEARCH_KEY = "UPDATE_SEARCH_KEY";
export const UPDATE_PRICE_RANGE = "UPDATE_PRICE_RANGE";
export const UPDATE_SORT_ORDER = "UPDATE_SORT_ORDER";
export const UPDATE_ITEM_STATE = "UPDATE_ITEM_STATE";
export const ERROR_MSG = "ERROR_MSG";
export const UPDATE_SCROLLBAR_LOADING = "UPDATE_SCROLLBAR_LOADING";
export const RESET_ITEM = "RESET_ITEM";
export const SHOW_Map_State = "SHOW_Map_State";

// task details
export const UPDATE_MAP_STATE = "UPDATE_MAP_STATE";
export const UPDATE_DETAIL_STATE = "UPDATE_DETAIL_STATE";
export const UPDATE_LOADING_STATE = "UPDATE_ISLOADING_STATE";
